AllCops:
  NewCops: enable

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Metrics:
  Enabled: false

Naming/VariableNumber:
  CheckSymbols: false

Style/Documentation:
  Enabled: false

Style/MutableConstant:
  Enabled: false
